name: CI
on: [push]

jobs:
  # rubocop:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Set up Ruby
  #     uses: ruby/setup-ruby@v1
  #     with:
  #       ruby-version: 2.6

  #   - name: Run rubocop
  #     run: bundle exec rubocop -P

  rspec:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby:
          - 2.5
          # - 2.6
          # - 2.7
          - 2
          # - '3.0'
          # - head
          # - jruby
          # - jruby-head
          # - truffleruby
          # - truffleruby-head]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run rspec
      run: bundle exec rspec
